### ISSUE TITLE
where is udoobludevice.connectAndSetUp?

### ISSUE THREAD

**Issue by dmars1972** [UDOOboard/node-udoo-blu#1]
startScanning
blu  b0b448c3c507
dd  b0b448c3c507
stopScanning
connectAndSetUp
/home/daniel/src/node-udoo-blu/testLed.js:25
            udoobludevice.connectAndSetUp(callback);
                          ^

TypeError: Cannot read property 'connectAndSetUp' of undefined
    at /home/daniel/src/node-udoo-blu/testLed.js:25:27
    at /home/daniel/node_modules/async/dist/async.js:3866:24
    at replenish (/home/daniel/node_modules/async/dist/async.js:998:17)
    at /home/daniel/node_modules/async/dist/async.js:1002:9
    at eachOfLimit (/home/daniel/node_modules/async/dist/async.js:1027:24)
    at /home/daniel/node_modules/async/dist/async.js:1032:16
    at _parallel (/home/daniel/node_modules/async/dist/async.js:3865:5)
    at Object.series (/home/daniel/node_modules/async/dist/async.js:4721:5)
    at testLed (/home/daniel/src/node-udoo-blu/testLed.js:22:11)
    at Timeout._onTimeout (/home/daniel/src/node-udoo-blu/testLed.js:18:5)

**Comment by L-I-Am** [comment]
I have the same issue, at almost every test it gives me this error... Did you perhaps find a way past it? or is it still an open question?
